export const INITIAL_GAME_STATE = {
    level: 1,
    money: 15000,
    missions: [
      {
        id: 1,
        title: "Mag Dilig ng 2 Crop",
        questions: {
          tagalog: "Bakit mahalaga ang wastong pagdidilig ng halaman?",
          english: "Why is it important to water plants properly?",
        },
        reward: 50,
        locked: false,
        completed: false,
        requiredMissionId: 1,
      },
      {
        id: 2,
        title: "Mag Dilig ng 3 Crop",
        questions: {
          tagalog: "Anong mga hakbang ang dapat gawin kung ang lupa sa inyong hardin ay tuyo, matigas, at bitak-bitak?",
          english: "What steps should you take if the soil in your garden is dry, hard, and cracked?",
        },
        reward: 50,
        locked: false,
        completed: false,
        requiredMissionId: 1,
      },
      {
        id: 3,
        title: "Mag Dilig ng 4 Crop",
        questions: {
          tagalog: "Paano mo masisiguro na natatanggap ng mga halaman ang sapat na sikat ng araw at tubig?",
          english: "How do you ensure that the plants receive adequate sunlight and water?",
        },
        reward: 50,
        locked: false,
        completed: false,
        requiredMissionId: 1,
      },
      {
        id: 4,
        title: "Mag tanim ng 2 Ornamental Plant",
        questions: {
          tagalog: "Ano ang mga pakinabang ng pagtatanim ng mga halamang ornamental sa inyong hardin o pamayanan?",
          english: "What are the benefits of planting ornamental plants in your garden or community?",
        },
        reward: 50,
        locked: false,
        completed: false,
        requiredMissionId: 2,
      },
      {
        id: 5,
        title: "Mag tanim ng 3 Ornamental Plant",
        questions: {
          tagalog: "Paano nakakatulong ang mga halamang ornamental at mga puno sa pagpigil ng pagguho ng lupa, pagbaha at pagpapanatili ng kalidad ng tubig?",
          english: "How do ornamental plants and trees help in preventing soil erosion, flooding, and maintaining water quality?",
        },
        reward: 50,
        locked: false,
        completed: false,
        requiredMissionId: 2,
      },
      {
        id: 6,
        title: "Mag tanim ng 4 Ornamental Plant",
        questions: {
          tagalog: "Paano nakakatulong ang mga halamang ornamental at mga puno sa pagpapababa ng polusyon sa hangin?",
          english: "How do ornamental plants and trees contribute to reducing air pollution?",
        },
        reward: 50,
        locked: false,
        completed: false,
        requiredMissionId: 2,
      },
      {
        id: 7,
        title: "Mag tanim ng 5 Ornamental Plant",
        questions:{
          tagalog: "Paano pinapaganda ng mga halamang ornamental ang isang lugar?",
          english: "How do ornamental plants enhance the aesthetic value of a place?",
        },
        reward: 50,
        locked: false,
        completed: false,
        requiredMissionId: 2,
      },
      {
        id: 8,
        title: "Mag tanim ng kahit anong Ornamental Plant",
        questions:{
          tagalog: "Bakit mahalagang pumili ng tamang halamang ornamental para sa inyong hardin?",
          english: "Why is it important to choose the right ornamental plants for your garden?",
        },
        reward: 50,
        locked: false,
        completed: false,
        requiredMissionId: 3,
      },
      {
        id: 9,
        title: "Gumamit ng Asarol",
        questions:{
          tagalog: "Ano ang mga karaniwang kasangkapan sa paghahalaman at ano ang kanilang gamit?",
          english: "What are the common tools used in gardening, and what are their purposes?" ,
        },
        reward: 50,
        locked: false,
        completed: false,
        requiredMissionId: 3,
      },
      {
        id: 10,
        title: "Gumamit ng Synthetic Fertilizer",
        questions:{
          tagalog: "Ano ang mga benepisyo ng paggamit ng organikong abono kumpara sa sintetikong pataba?",
          english: " What are the benefits of using organic fertilizer compared to synthetic fertilizers? ",
        },
        reward: 50,
        locked: false,
        completed: false,
        requiredMissionId: 4,
      },
      {
        id: 11,
        title: "Gumawa ng Organic Fertilizer",
        questions:{
          tagalog: "Bakit mahalaga ang pagpili ng angkop na lokasyon para sa compost pit?",
          english: "Why is it essential to choose an appropriate location for a compost pit?",
        },        
        reward: 50,
        locked: false,
        completed: false,
        requiredMissionId: 4,
      },
      {
        id: 12,
        title: "Gumamit ng Organic Fertilizer",
        questions:{
          tagalog: "Ano ang mga benepisyo at kahinaan ng paggamit ng organic na pataba sa gardening?",
          english: "What are the advantages and disadvantages of using organic fertilizers in gardening?",
        },
        reward: 50,
        locked: false,
        completed: false,
        requiredMissionId: 4,
      },
      {
        id: 13,
        title: "Mag tanim ng tree",
        questions:{
          tagalog: "Bakit mahalaga ang mga puno sa kapaligiran at sa buhay ng tao?",
          english: "Why are trees important for the environment and human life?" ,
        },
        reward: 50,
        locked: false,
        completed: false,
        requiredMissionId: 5,
      },
      {
        id: 14,
        title: "Mag Benta ng Fresh Plants",
        questions:{
          tagalog: "Bakit mahalaga ang magkaroon ng regular na suplay ng prutas sa merkado?",
          English: "Why is it important to maintain a consistent supply of fruit in the market?",
        },
        reward: 50,
        locked: false,
        completed: false,
        requiredMissionId: 5,
      },
      {
        id: 15,
        title: "Mag tanim ng 2 crops",
        questions: {
          tagalog: "Paano nakatutulong ang mga prutas sa suplay ng pagkain ng komunidad?",
          english: "How do fruit-bearing trees contribute to the communitys food supply?",
        },
        reward: 50,
        locked: false,
        completed: false,
        requiredMissionId: 5,
      },
      {
        id: 16,
        title: "Mag sell ng prutas",
        questions: {
          tagalog: "Paano maaaring pagkakitaan ng mga pamilya ang mga halamang ornamental?",
          english: "How can ornamental plants be used as a source of income for families",
        },
        reward: 50,
        locked: false,
        completed: false,
        requiredMissionId: 5,
      },
    ],
    inventory: [],
    statistics: {
      plantsGrown: 0,
      moneyEarned: 0,
      missionsCompleted: 0,
    },
  };
  
  export const SHOP_ITEMS = [
    // {
    //   id: 0,
    //   title: 'Itakv2',
    //   type: 'tool',
    //   description: 'Used for cutting plants or Harvesting',
    //   image: require('@/assets/images/itak.png'),
    //   price: 0,
    // },
    {
      id: 1,
      title: "Asarol",
      description: "Used for tilling soil",
      price: 10,
      type: "tool",
      image: require('@/assets/images/asarol1.png'),
    },
    {
      id: 2,
      title: "Itak",
      description: " Used for cutting plants or Harvesting",
      price: 10,
      type: "tool",
      image: require('@/assets/images/itak.png'),
    },
    {
      id: 3,
      title: "Regadera",
      description: "Used for watering plants",
      price: 10,
      type: "tool",
      image: require('@/assets/images/regadera.png'),
    },
    {
      id: 4,
      title: "Sibuyas",
      description: "A common vegetable crop",
      price: 10,
      type: "crop",
      image: require('@/assets/images/sibuyas.png'),
    },
    {
      id: 5,
      title: "Mangga",
      description: "Bears sweet mango fruits",
      price: 100,
      type: "tree",
      image: require('@/assets/images/mangga.png'),
    },
    {
      id: 6,
      title: "Carrot",
      description: "A root vegetable crop",
      price: 70,
      type: "crop",
      image: require('@/assets/images/karot.png'),
    },
    {
      id: 7,
      title: "Gumamela",
      description: "A flowering ornamental plant",
      price: 200,
      type: "crop",
      image: require('@/assets/images/gumamela.png'),
    },
    {
      id: 8,
      title: "Chemical Pesticide",
      description: "Used to protect crops from pests and insects",
      price: 100,
      type: "tool",
      image: require('@/assets/images/chemical.png'),
    },
    {
      id: 9,
      title: "Synthetic Fertilizer",
      description: "Improves soil nutrients for better crop growth",
      price: 100,
      type: "tool",
      image: require('@/assets/images/fertilizer.png'),
    },
    {
      id: 10,
      title: "Kamatis",
      description: "A juicy red tomato, perfect for salads and sauces.",
      price: 80,
      type: "crop",
      image: require('@/assets/images/kamatis.png'),
    },
    {
      id: 11,
      title: "Santan",
      description: "A vibrant flowering plant known for its sweet nectar.",
      price: 100,
      type: "crop",
      image: require('@/assets/images/santan.png'),
    },
    {
      id: 12,
      title: "Orchids",
      description: "Elegant and exotic flowers admired for their beauty.",
      price: 100,
      type: "crop",
      image: require('@/assets/images/orchid.png'),
    },
    {
      id: 13,
      title: "Saging",
      description: "A nutritious banana plant, great for snacks and desserts.",
      price: 85,
      type: "crop",
      image: require('@/assets/images/saging.png'),
    },
    {
      id: 14,
      title: "Papaya",
      description: "A tropical fruit rich in vitamins and known for its sweet taste.",
      price: 75,
      type: "crop",
      image: require('@/assets/images/papaya.png'),
    },
  ];